# Generated by Django 3.1.5 on 2021-01-25 07:50

from django.db import migrations, models
import store_user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('email', models.EmailField(max_length=150, unique=True, verbose_name='آدرس ایمیل')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='موبایل')),
                ('avatar', models.ImageField(blank=True, default='default_images/avatar/avatar.jpg', null=True, upload_to=store_user.models.upload_avatar_user, verbose_name='تصویر')),
                ('code_meli', models.CharField(blank=True, max_length=10, null=True, verbose_name='کد ملی')),
                ('ostan', models.CharField(blank=True, max_length=50, null=True, verbose_name='استان')),
                ('shahr', models.CharField(blank=True, max_length=70, null=True, verbose_name='شهر')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('join_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ثبت نام')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیر فعال')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='ادمین')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
            },
        ),
    ]
