# Generated by Django 3.1.5 on 2021-02-04 16:38

from django.db import migrations, models
import django.db.models.deletion
import store_shop.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=store_shop.models.upload_gallery_image)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='نام تگ')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضبحات')),
                ('price', models.PositiveBigIntegerField(default=0.0, verbose_name='قیمت')),
                ('active', models.BooleanField(default=True, verbose_name='فعال / غیر فعال')),
                ('exists', models.BooleanField(default=True, verbose_name='موجود / نا موجود')),
                ('visit', models.IntegerField(default=0, verbose_name='بازدید ها')),
                ('register_date', models.DateTimeField()),
                ('image', models.ImageField(upload_to=store_shop.models.upload_product_image, verbose_name='تصویر اصلی')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_shop.category', verbose_name='دسته بندی')),
                ('feature', models.ManyToManyField(blank=True, to='store_shop.Feature')),
                ('gallery', models.ManyToManyField(to='store_shop.Gallery', verbose_name='گالری تصاویر')),
                ('tag', models.ManyToManyField(blank=True, to='store_shop.Tag')),
            ],
        ),
    ]
