# Generated by Django 3.1.5 on 2021-02-04 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='exists',
            new_name='available',
        ),
    ]
