# Generated by Django 3.1.5 on 2021-02-04 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_shop', '0002_auto_20210204_2014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='available',
            new_name='is_available',
        ),
    ]
